server:
  port: 8999

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
           - name: CircuitBreaker
             args:
               name: user-service
               fallbackuri: forward:/userServiceFallback


        - id: contact-services
          uri: lb://contact-service
          predicates:
            - Path=/contact/**
          filters:
            - name: CircuitBreaker
              args:
               name: contact-service
               fallbackuri: forward:/contactServiceFallback


#If service not respond in 5000 milisecond the it will down so for this we write below code
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#to Moniter stream and expose dend point stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream